In [3]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [5]:
test_list1 = [1, 4, 5, 6, 5] 
test_list2 = [3, 5, 7, 2, 5] 
for i in test_list2 : 
    test_list1.append(i) 
print ("Concatenated  : "+ str(test_list1))

Concatenated  : [1, 4, 5, 6, 5, 3, 5, 7, 2, 5]


In [6]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [7]:
import numpy as np 
  
ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) 
print("initial array", str(ini_array1)) 
result = ini_array1.flatten() 
print("New resulting array: ", result) 

initial array [[1 2 3]
 [2 4 5]
 [1 2 3]]
New resulting array:  [1 2 3 2 4 5 1 2 3]
